openapi: 3.0.1
info:
  title: Football Notitia
  description: A plugin that helps the user to get recent and accurate infomation about footbal using ChatGPT.
  version: 'v1'
servers:
  - url: https://football-plugin.onrender.com
paths:
  /api/v1/players:
    get:
      operationId: getTeamPlayers
      summary: Get the list of players for the team
      parameters:
      - in: query
        name: league_name
        schema:
            type: string
        required: true
        description: The name of the league.
      - in: query
        name: country_name
        schema:
            type: string
        required: true
        description: The name of the country where the leauge belongs.
      - in: query
        name: team_name
        schema:
            type: true
        required: true
        description: The name of the team

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getTeamPlayersResponse'
        
        "400":
          description: Query parameters were not provided
        "404":
          description: The league was not found
        "500":
          description: Internal server error

  /api/v1/players/top-scorers:
    get: 
      operationId: getTopScorers
      summary: Get the list of top goalscorers in a league.
      parameters:
        - in: query
          name: league_name
          schema:
              type: string
          required: true
          description: The name of the league.
        - in: query
          name: country_name
          schema:
              type: true
          required: true
          description: The name of the country where the leauge belongs.

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getTopScorersResponse'
  
        "400":
          description: Query parameters were not provided
        "404":
          description: The league was not found
        "500":
          description: Internal server error

      x-code-samples:
        - lang: curl
          source: |
             curl -X GET 'https://football-plugin.onrender.com/api/v1/players/top-scorers?league_name=La Liga&country_name=Spain'


  /api/v1/teams:
    get: 
      operationId: getTeams
      summary: Get the list of teams in a league.
      parameters:
        - in: query
          name: league_name
          schema:
              type: string
          required: true
          description: The name of the league.
        - in: query
          name: country_name
          schema:
              type: true
          required: true
          description: The name of the country where the leauge belongs.

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getTeamsResponse'

        "400":
          description: Query parameters were not provided
        "404":
          description: The league was not found
        "500":
          description: Internal server error

      x-code-samples:
        - lang: curl
          source: |
             curl -X GET 'https://football-plugin.onrender.com/api/v1/teams?league_name=Premier League&country_name=England'


components:
  schemas:
    getTeamPlayersResponse:
      type: array
      items:
        type: object
        properties:
          player_name: 
            type: string
          player_number:
            type: string
          player_type:
            type: string
          player_age:
            type: string
          player_match_played:
            type: string
          player_goals:
            type: string
          player_yellow_cards:
            type: string
          player_red_cards:
            type: string
          player_image:
            type: string
    
    getTopScorersResponse:
      type: array
      items:
        type: object
        properties:
           player_place:
             type: integer
           player_name:
             type: string
           team_name:
             type: string
           goals:
             type: integer
           assists:
             type: integer
           penality_goals:
             type: integer

    getTeamsResponse:
      type: array
      items:
        type: object
        properties:
           team_name:
             type: string
           team_logo:
             type: string
           team_coach:
             type: string